FROM ubuntu:focal
WORKDIR /KSK
EXPOSE 5000
COPY    ./requirements.txt  ./
RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.6 python3-distutils python3-pip python3-apt
RUN pip3 install -r requirements.txt
COPY ./ ./
CMD [ "python3","run.py" ]